[pytest]
addopts = -s -v --alluredir=allure-results
markers =
    route_drawing:    Тесты отрисовки маршрута
    route_block:      Блок с выбором маршрута
    prepare_taxi:     Подготовка к заказу такси
    taxi_full:        Полный флоу заказа такси
    taxi_order:       Тесты формы заказа такси
xfail_strict = true        
